site_name:           MesoscaleML
repo_url:            https://github.com/upiterbarg/MesoscaleML.jl.git
site_description:    Documentation for the Julia package MesoscaleML.jl
site_author:         Ulyana Piterbarg
theme:               readthedocs

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  
extra_css:
  - assets/Documenter.css

docs_dir: 'src'

nav:
- Introduction: index.md